# non-network params
max_camera_lidar_delay: 0.12
# plugins
plugins_path: "$(find bevfusion)/../../devel/lib/libautoware_tensorrt_plugins.so"
# network
trt_precision: fp16
cloud_capacity: 2000000
# pre-process params
densification_num_past_frames: 3
densification_world_frame_id: lidar_top
# post-process params
circle_nms_dist_threshold: 0.5
iou_nms_search_distance_2d: 10.0
iou_nms_threshold: 0.1
yaw_norm_thresholds: [0.3, 0.3, 0.3, 0.3, 0.0] # refers to the class_names
score_threshold: 0.1
