class_names: ["CAR", "TRUCK", "BUS", "BICYCLE", "PEDESTRIAN"]
voxels_num: [1, 200000, 350000] # [min, opt, max]
point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0] # [x_min, y_min, z_min, x_max, y_max, z_max]
voxel_size: [0.075, 0.075, 0.2] # [x, y, z]
num_proposals: 500
out_size_factor: 8
max_points_per_voxel: 10
num_point_feature_size: 4

d_bound: [1.0, 60.0, 0.5]
x_bound: [-54.0, 54.0, 0.3]
y_bound: [-54.0, 54.0, 0.3]
z_bound: [-10.0, 10.0, 20.0]
num_cameras: 6
raw_image_height: 900
raw_image_width: 1600
img_aug_scale_x: 0.489
img_aug_scale_y: 0.489
roi_height: 384
roi_width: 704
features_height: 48
features_width: 88
num_depth_features: 118
